### ISSUE TITLE
Rotating folks for GB Developer Seat 

### ISSUE THREAD

**Issue by dims** [kubernetes/steering#178]
From https://github.com/cncf/foundation/blob/master/maintainers-election-policy.md#gb-developer-seat-eligibility:
```
The Kubernetes Steering Committee will determine its own method for selecting the representative, though CNCF is happy to organize an election for it if requested.
```

I think it would be good to periodically rotate folks service on the GB on behalf of Kubernetes Steering. Currently @michelleN is our rep. 

Should we setup some guidelines/policies around term/selection etc?

**Comment by michelleN** [comment]
Setting up guidelines for selection sounds great and a description of the responsibility (influence marketing decisions and operations by representing the KSC perspective) would be good too. Definitely good to be transparent about how the dev rep is selected from KSC. As the first one, I gotta say I really had no idea what I was getting into. No one else on the KSC really wanted to do it and I just figured I had had experience with the CNCF before as KubeCon chair so I was happy to help.

I was selected for a 1 year term initially and then re-elected for a 2 year term. The term of a developer rep is 2 years ([outlined in the charter](https://github.com/cncf/foundation/blob/master/maintainers-election-policy.md#developer-representation-on-the-cncf-gb)) so that the terms of the two developer reps on the GB can be staggered. This is nice because both of the reps are never new to the board at the same time and because there can be knowledge/context sharing.

As a developer who had not been exposed to boards previously, it took me a long time to understand how the GB functions, get to know people on the GB, and understand how to affect change so I appreciated having the multi year term (esp since the GB meets only ~4-5 times a year). If the KSC wants to propose a change to the term of the developer rep, I'd be happy to chat more about proposing that to the GB. I do think there is merit to having a 2 year term for the reasons listed above.

[This](https://github.com/cncf/toc/issues/209) is an example of how we did the TOC chair nomination/election btw.

**Comment by dims** [comment]
@michelleN thanks for the quick response. How much time do we to set this all up?

**Comment by michelleN** [comment]
I believe my term ends in December but I can't remember the exact date. November would be my last GB meeting. Maybe @caniszczyk could help us out with the date?

**Comment by caniszczyk** [comment]
@michelleN 12/15 for the seat

In regards to deciding who should serve as the rep, one simple pattern used often in our projects, the chair of the SC/TOC/TAC/TSC etc gets a seat on a representative board. Has the k8s SC considered having a chair that serves some type of role?

Otherwise, we are happy to run a simple election for you or you can decide via consensus.

I agree with you that a 2 year term is better to make a viable impact (like you did in pushing for publishing minutes).

**Comment by parispittman** [comment]
discussed in steering meeting today: @dims  will put a call out to steering@kubernetes.io for interested emeritus and current members Oct 1; Steering will vote tbd on process

**Comment by dims** [comment]
@parispittman done! https://groups.google.com/a/kubernetes.io/g/steering/c/I4nBjyfLmXE/m/l55rYxxwAAAJ

**Comment by caniszczyk** [comment]
friendly poke here given 12/15 for the seat

**Comment by caniszczyk** [comment]
@dims any update?

**Comment by dims** [comment]
@caniszczyk - @jberkus @mrbobbytables will be running an election, i'll let them chime in here.

**Comment by jberkus** [comment]
We will conduct a an election among the Steering Committee folks starting on January 15th and ending 5 days later.  The current candidates are:

* Paris Pittman
* Aaron Crickenberger
* Davanum Srinivas

This will also be a functional test of our new elections system.

**Comment by dims** [comment]
@jberkus please add @timothysc as well https://kubernetes.slack.com/archives/CPNFRNLTS/p1607462287121800

**Comment by jberkus** [comment]
OK

**Comment by dims** [comment]
@caniszczyk please see the results here:
https://groups.google.com/a/kubernetes.io/g/steering/c/Mu8ZP363GGg/m/6_QpidyGDAAJ

@parispittman will be representing k8s-steering in the CNCF GB.

![image](https://user-images.githubusercontent.com/23304/104541998-b6a96980-55f0-11eb-9f65-c8adb65c14b0.png)

**Comment by dims** [comment]
Thanks @jberkus and @mrbobbytables for running the election! and Manish (@kalkayan) for the spanking brand new election app.

/close
