### ISSUE TITLE
Annual Reports Actions and Wrap Up 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#207]
Issue to collect our notes from the summary and meetings about actions we need to take for next year as well as topics that need to have follow up:

**Build:**
- creating a template and a generator of some kind so it's not a manual add for the summary by steering and better user experience for the survey taker
  - cc/ @cblecker 
  - 
- script or some other automated way that suggests folks to promote into owners files and who is no longer active to help sig leaders
  - https://github.com/cncf/devstats/issues/299 - can we get this one done?
- ?

**Look into:**
- how to do better outreach to inform chairs and deadlines
  - post schedule to markdown in policy and then link to #chairs-and-techleads, leads@, steering@
  - make sure there are clear actions and steps 
  - link up with contributor-comms 
  - create: k8s.dev/reports
- creating a devstats dashboard for each sig with the populated dashboards that steering cares about and automation around the things we have APIs for like YouTube and automate the entire "operational" section
  - https://github.com/cncf/devstats/issues/229 - should we play off of this?
  - could we use lfx mentees or other mentoring groups? 
  - 
- ?

**Follow up:**
- ask psc member / sig security to come to a chair/tl meeting for how to handle a cve response and q&a/feedback between groups (this came from annual reports from multiple sig chairs)
  - Paris asked Tabitha and Tim their thoughts and trying to schedule for Dec Chairs/TLs meeting 
- ?

**Discussion needed; Decisions to follow up in PRs:**
- some wgs don't report into all of their sponsoring sigs; does this matter? some wgs have many - can we help streamline this?
- more meeting cadence: do sigs that are in a near maintenance mode need to have the same requirements? 
- ?

**Comment by tpepper** [comment]
A couple notes:

```some wgs don't report into all of their sponsoring sigs; does this matter? some wgs have many - can we help streamline this?```

I definitely think this matters.  As _a_ (singular) project we need to all give some attention to cohesion.  IMHO WGs must keep their sponsor, and just "adjacent", SIGs informed.

As a past SIG and WG chair I really wished for a standard way of setting a reminder, a cron job of sorts, for all sorts of coordination activities, eg: check in with my sponsor/adjacent SIG, check for newly activated folks who might should be reviewers, check for reviewer-to-approver promotion candidates, annual check for new TL or Chair candidates, etc., etc.  There is a tonne of leadership activity that is ongoing, but easily always at the end of the to-do list and thus not done as regularly as it should be.  Sure this may just come down to a personal need to be well organized.  But could we do some automated reminders?  Would that help, or just get lost in the noise?

```more meeting cadence: do sigs that are in a near maintenance mode need to have the same requirements?```

I can see giving some (informal?) allowance, if the SIG/WG has formally indicated it has slowed but still has some outstanding deliverable which is not easily shifted under another SIG as a subproject.  I worry that the allowance alone becomes a causal/contributing source of silence and shutdown, instead of being a trailing recognition of pending shutdown.  If established folks think things are mostly done, but newcomers don't have a place to voice their ideas, we risk prematurely ending collaboration possibilities.

**Comment by justaugustus** [comment]
Assigning Jordan and myself for this [agenda doc item](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit?disco=AAAARHMIAP4):

> Jordan+Stephen: look at last year’s reports, specifically note the things for which there was not a tool and that meant human toil, give concrete ask instead of broad help to devstats dev

/assign @liggitt @justaugustus

**Comment by parispittman** [comment]
quick notes re: @liggitt  comments above, numbered by bullet

1 - add to liaison duties
2 - we don't have community meeting requirements anymore so liaison will need to ask this question and then pull whatever it is - kubecon, email to sig list, etc. 
3 - add to liaison duties
4 - add to liaison duties to pull devstats for the sig; keep the second half of the question open since that's a key part of the summary since the audience is most end users and heavy contributors
5 - if we add to liaison duties - how can they pull that easily?
6 - same question as #5
7 and 8 - add to liaison duties to help their sig come up with a process for subproject check ins
9 - add to liaison list to pull a delta of changes from sigs.yaml
10 - @dims  to solidify tooling and advertise

**Comment by parispittman** [comment]
we have open issues or it's done so this is safe to close

/close
