### ISSUE TITLE
Security Audit for Kubernetes on behalf of CNCF

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#71]
The CNCF has been piloting a security audit program for CNCF projects:

https://coredns.io/2018/03/15/cure53-security-assessment/
https://github.com/envoyproxy/envoy#security-audit
https://cure53.de/pentest-report_prometheus.pdf

The pilot has been successful and we are happy to start offering this to other CNCF projects that are interested. We would give preference to graduated projects first. After speaking with @bgrant0607 a bit he suggested making this a KSC topic, so here we are.

**Comment by jessfraz** [comment]
can we get a company that has a proven track record like NCC group or something... ping @dyn- @killahertz who did the docker one, but no longer work there and may know of good people...

**Comment by jessfraz** [comment]
ah no it's @jhertz , sorry for the noise

**Comment by jessfraz** [comment]
also @tqbf and @ddz

(I would like to find a legit company otherwise it's not worth it, not that that other company is not legit just I have not heard of it... someone correct me if I'm wrong... :)

**Comment by jessfraz** [comment]
I would like to just put for comparison sake the quality of the work from NCC group, versus the links Chris gave above... I looked them over...

https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/2016/june/container_whitepaper.pdf
https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/2016/april/ncc_group_understanding_hardening_linux_containers-1-1.pdf

**Comment by caniszczyk** [comment]
happy to use whatever vendor the KSC prefers, CNCF is happy to make it happen

**Comment by ddz** [comment]
Cure53 is actually very good. They have been very good about publishing their audit reports of open source projects (not many security companies do this) and their findings in the linked reports look very solid to me.

**Comment by j3ssb0t** [comment]
Thanks @ddz that's super helpful and gives me a lot more confidence :)

**Comment by jessfraz** [comment]
Thanks @ddz that's super helpful and gives me a lot more confidence :)

**Comment by philips** [comment]
I have only helped lead two third party security audits in my career but I think the process for selection should be something like this:

## Customer Audit Team

- Form a team of 2-3 Kubernetes people to lead the process (audit leads)
- Audit leads create a list of 5-10 focus areas (likely based on the bug bounty scope cc @tallclair)
- Identify 5-10 kube contributors on a subject matter experts (SMEs) on the focus areas

## Evaluate Vendor Teams

- Identify 2-3 vendors to evaluate
- Get resumes/CVs/reports of the lead and supporting audit team (I think this is important because with all due respect to the vendors the makeup of the team is more important than the brand of the vendor)
- Let the audit leads choose the vendor based on their past experience and the desired focus areas.

## Work with Vendor

- Establish a kickoff meeting where the audit leads train the vendor team on the product architecture, build process, and getting things running
- Establish regular weekly or bi-weekly sync during engagement between audit leads and vendor
- Engage SMEs as necessary to provide context and help guide the vendor
- Disclose urgent issues to the existing security@kubernetes.io processes

## Report Out

- The audit leads should do review rounds on drafts of the report along with the SMEs, and Kubernetes Product Security Team providing feedback to the vendor 
- Audit leads work with PST to decide on responsible day to open the final draft up publicly

If people think this is roughly right I can put together a Google Doc to work on.

**Comment by philips** [comment]
FWIW, I have worked with Matasanto, NCC, and received a recommendation for Cure53 from someone I trust.

That said I deeply believe it is the individuals and not the vendor brand that matters and their fit to the engagement.

**Comment by jessfraz** [comment]
This all sounds great to me and I agree it's the individual researchers who matter not vendor :)

**Comment by philips** [comment]
Steering committee: would you mind delegating vendor selection
responsibility to a 2-3 person audit team selected by the [PST](
https://github.com/kubernetes/sig-release/blob/master/security-release-process-documentation/security-release-process.md#product-security-team-pst)?
It might not be people from the PST but we could help find the right folks.

**Comment by joelsmith** [comment]
We used Insomnia Security for an engagement specific to OpenShift and they did a fantastic job. They uncovered privilege escalation vector in our build system and made lots of other recommendations. They have a working knowledge of k8s owing to the work they did for Red Hat. I can provide the name of the lead researcher upon request.

**Comment by philips** [comment]
Through lazy consensus the steering committee has delegated forming a security audit team to the PST. 

I think the next step is to solicit volunteers to run the audit from folks on SIG Auth and the PST. Relevant questions:

- What experience do you have with a third party security audit?
- What experience do you have with the subsystems of Kubernetes that will likely be in scope based on the [bug bounty definition draft](https://github.com/kubernetes/community/blob/4523667ee64461e5424cb8345facbe7335a3a0f1/contributors/guide/bug-bounty.md#in-scope)
- Will you have support of your employer to spend about 8-12 hours in total over 4-6 weeks in support of this audit?

**Comment by philips** [comment]
Moving discussion to SIG Release Issue https://github.com/kubernetes/sig-release/issues/284

**Comment by philips** [comment]
The team had their first meeting: https://groups.google.com/forum/#!topic/kubernetes-sig-auth/DOHShVCW6RM

**Comment by joelsmith** [comment]
FYI, @jessfraz has stepped down as one of the wg leaders since she's too busy now, and the PST has selected Craig Ingram @cji to replace her.

**Comment by miskun** [comment]
So, is the plan to limit the scope on K8S "kernel" only or is there plan to provide security audit also for more complete solutions? I'm talking about K8S distros. If so, we'd like to be involved.

**Comment by philips** [comment]
I am going to close this out since it has been delegated to https://github.com/kubernetes/community/tree/master/wg-security-audit and the work is underway.

/close
